version: '3.7'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - todo-network

  loki:
    image: grafana/loki:2.3.0
    ports:
      - target: 3100
        published: 3100
        protocol: tcp
        mode: host
    user: root
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - todo-network

  grafana:
    image: grafana/grafana:8.1.0
    ports:
      - "3001:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
